backend/JiShop/src/main/java/com/jishop/common/exception/DomainException.java, backend/JiShop/src/main/java/com/jishop/common/exception/ExceptionController.java, backend/JiShop/src/main/java/com/jishop/controller/impl/exampleControllerImpl.java, backend/JiShop/src/main/java/com/jishop/service/impl/exampleServiceImpl.java
=> [BE] Jishop 초기세팅

backend/JiShop/src/main/java/com/jishop/controller/OAuthController.java, backend/JiShop/src/main/java/com/jishop/controller/impl/GoogleControllerImpl.java, backend/JiShop/src/main/java/com/jishop/controller/impl/KakaoControllerImpl.java, backend/JiShop/src/main/java/com/jishop/controller/impl/NaverControllerImpl.java, backend/JiShop/src/main/java/com/jishop/dto/NoticeResponse.java, backend/JiShop/src/main/java/com/jishop/service/AbstractOAuthService.java, backend/JiShop/src/main/java/com/jishop/service/impl/GoogleServiceImpl.java, backend/JiShop/src/main/java/com/jishop/service/impl/KakaoServiceImpl.java, backend/JiShop/src/main/java/com/jishop/service/impl/NaverServiceImpl.java, backend/JiShop/src/main/resources/static/index.html
- resolves #15 
---
- AbstractOAuthService.java 파일 추가
- index.html 구조 조정
- AbstractOAuthService.java에 맞춰서 ServiceImpl 코드 수정
- 의존성 주입 문제가 있었습니다
- application.yml 파일을 불러오지 않아서 난 에러였기에 pull 함으로써 해결했습니다
- 어느 부분을 더 추상화 할 수 있을 지 고민해주세요!
-
=> [BE] 소셜 로그인 추상화 V2

backend/log/src/main/java/com/example/log/common/util/BaseEntity.java, backend/log/src/main/java/com/example/log/config/AsyncConfig.java, backend/log/src/main/java/com/example/log/controller/LogController.java, backend/log/src/main/java/com/example/log/controller/exampleController.java, backend/log/src/main/java/com/example/log/controller/impl/LogControllerImpl.java, backend/log/src/main/java/com/example/log/controller/impl/exampleControllerImpl.java, backend/log/src/main/java/com/example/log/domain/Log.java, backend/log/src/main/java/com/example/log/domain/enums/UserActionType.java, backend/log/src/main/java/com/example/log/domain/exampleEntity.java, backend/log/src/main/java/com/example/log/dto/LogRequest.java, backend/log/src/main/java/com/example/log/dto/exampleRequest.java, backend/log/src/main/java/com/example/log/dto/exampleResponse.java, backend/log/src/main/java/com/example/log/repository/LogRepository.java, backend/log/src/main/java/com/example/log/repository/exampleRepository.java, backend/log/src/main/java/com/example/log/service/LogQueue.java, backend/log/src/main/java/com/example/log/service/LogService.java, backend/log/src/main/java/com/example/log/service/exampleService.java, backend/log/src/main/java/com/example/log/service/impl/LogServiceImpl.java, backend/log/src/main/java/com/example/log/service/impl/exampleServiceImpl.java, backend/log/src/test/java/com/example/log/LogServiceTest.java
🔗 Resolves: #20
- resolves #20 
---
- 로그를 저장하는 기능
- 없습니다.
- 없습니다.
- .
-
=> [BE] 로그 저장 MVP1 구현 #20

backend/log/src/main/java/com/example/log/controller/impl/LogControllerImpl.java
- resolves #22 
---
- 로그 기능을 구현했다.
- 요청으로 보낸 json이 java 객체로 변환이 안되어 필드값이 null 상태로 저장이 됌.. 
- 서버에 데이터가 저장이 안되고 그냥 200 만 응답한다.
- @RequestBody추가 
- controller에서 service를 사용하지 않았기 때문 !!!
- 서비스 테스트 만 했기 때문에 이 부분을 놓쳤다. ㅜㅜ
- .
- .
=> [BE] 로그 저장 MVP1 구현

backend/log/src/main/resources/docker-compose.yml, backend/log/src/main/resources/k6-scripts/stress.js, backend/log/src/main/resources/k6-scripts/test.js
- docker compose 파일 추가
🔗 Resolves: #32
- resolves #32 
---
- 부하 테스터 도구 k6 기능 구현
- k6를 시각화하기 위해 grafana, influxdb를 사용하면서 모니터링 설정할 때 연결이 안되는 문제
- 블로그, gpt 해결
- 
-
=> [BE] 사용자 로그 K6, Grafana 테스트

backend/JiShop/src/main/java/com/jishop/common/exception/ErrorType.java, backend/JiShop/src/main/java/com/jishop/controller/impl/SmsControllerImpl.java, backend/JiShop/src/main/java/com/jishop/service/impl/SmsServiceImpl.java
- Controller에서 ServiceImpl을 사용하고 있어 Sevice로 바꿨습니다
- SMS 문자 보내기 실패 오류 타입을 추가하였습니다
-
- 
- 
-
=> [BE] refactor: 문자 인증 구현 코드 리펙토링

backend/JiShop/src/main/java/com/jishop/common/exception/ErrorType.java, backend/JiShop/src/main/java/com/jishop/common/exception/ExceptionController.java, backend/JiShop/src/main/java/com/jishop/order/controller/OrderController.java, backend/JiShop/src/main/java/com/jishop/order/controller/OrderControllerImpl.java, backend/JiShop/src/main/java/com/jishop/order/domain/Order.java, backend/JiShop/src/main/java/com/jishop/order/domain/OrderDetail.java, backend/JiShop/src/main/java/com/jishop/order/domain/OrderNumber.java, backend/JiShop/src/main/java/com/jishop/order/domain/OrderStatus.java, backend/JiShop/src/main/java/com/jishop/order/dto/OrderDetailRequest.java, backend/JiShop/src/main/java/com/jishop/order/dto/OrderDetailResponse.java, backend/JiShop/src/main/java/com/jishop/order/dto/OrderRequest.java, backend/JiShop/src/main/java/com/jishop/order/dto/OrderResponse.java, backend/JiShop/src/main/java/com/jishop/order/repository/OrderNumberRepository.java, backend/JiShop/src/main/java/com/jishop/order/repository/OrderRepository.java, backend/JiShop/src/main/java/com/jishop/order/service/OrderNumberService.java, backend/JiShop/src/main/java/com/jishop/order/service/OrderNumberServiceImpl.java, backend/JiShop/src/main/java/com/jishop/order/service/OrderService.java, backend/JiShop/src/main/java/com/jishop/order/service/OrderServiceImpl.java
- `OrderRequest` DTO 를 통해 주문 요청 전송한다
- `Order` 엔티티를 생성하고, 요청된 각 상품에 대해서 `Product`를 조회한다
- 각 상품에 대한 `OrderDetail`을 생성하고 총 주문 금액을 계산하고 대표 상품명을 설정한다
- `Order` 정보 업데이트 및 저장한다
- 사용자가 주문ID 혹은 전체 주문 조회 요청을 한다
- `OrderServiceImpl`에서 주문 정보를 조회한다
- `OrderDetailResponse`를 생성하고 `OrderResponse`를 반환한다
- 사용자가 주문ID로 취소 요청을 보낸다
- `OrderServiceImpl`에서 주문 존재 여부를 확인하고, 취소 가능 상태를 확인한다
- 취소 가능하다면 주문 상태를 변경한다
- 상품 ID로만 주문 생성을 하려고 초반에 Product를 대충 만들었었는데 하다보니 주문 대표명을 위한 이름, 가격도 필요하여 더 추가로 만들어야했다
- 주문과 주문 상세를 동시에 만들다보니까 너무 헷갈렸다. request와 response만 해도 dto가 한가득 ㅠ
OrderRequest: 주문 생성 요청 데이터
OrderResponse: 주문 조회 응답 데이터
OrderDetailRequest: 주문 상세 요청 데이터
OrderDetailResponse: 주문 상세 응답 데이터
- 코드 추가를 해서 해결했다.  첨부터 꼼꼼히 봤다면 일을 두번 안해도 된건데!
- 종이에 적어가면서 최대한 흐름을 보려고 했다
- 주문의 흐름에 따라 봐주세요!
- 의연님의 주문 DTO들을 참고하였습니다!
=> [BE] 주문 기능 구현

backend/JiShop/src/main/java/com/jishop/member/controller/SignUpController.java, backend/JiShop/src/main/java/com/jishop/member/controller/SignUpControllerImpl.java, backend/JiShop/src/main/java/com/jishop/member/controller/UserController.java, backend/JiShop/src/main/java/com/jishop/member/controller/UserControllerImpl.java, backend/JiShop/src/main/java/com/jishop/member/dto/request/FindUserRequest.java, backend/JiShop/src/main/java/com/jishop/member/dto/response/FindUserResponse.java, backend/JiShop/src/main/java/com/jishop/member/repository/UserRepository.java, backend/JiShop/src/main/java/com/jishop/member/service/UserService.java, backend/JiShop/src/main/java/com/jishop/member/service/UserServiceImpl.java
=> [BE] 회원 id 찾기 구현

backend/JiShop/src/main/java/com/jishop/member/controller/AuthController.java, backend/JiShop/src/main/java/com/jishop/member/controller/UserController.java, backend/JiShop/src/main/java/com/jishop/member/controller/impl/AuthControllerImpl.java, backend/JiShop/src/main/java/com/jishop/member/controller/impl/UserControllerImpl.java, backend/JiShop/src/main/java/com/jishop/member/domain/User.java, backend/JiShop/src/main/java/com/jishop/member/dto/request/UserNameRequest.java, backend/JiShop/src/main/java/com/jishop/member/dto/request/UserPhoneRequest.java, backend/JiShop/src/main/java/com/jishop/member/dto/response/UserResponse.java, backend/JiShop/src/main/java/com/jishop/member/service/AuthService.java, backend/JiShop/src/main/java/com/jishop/member/service/UserService.java, backend/JiShop/src/main/java/com/jishop/member/service/impl/AuthServiceImpl.java, backend/JiShop/src/main/java/com/jishop/member/service/impl/UserServiceImpl.java
🔗 Resolves: #76
- 회원 정보 수정 -> 이름, 전화번호
- 회원 정보 조회
=> [BE] 마이페이지 구현

backend/JiShop/src/main/java/com/jishop/config/WebConfig.java, backend/JiShop/src/main/java/com/jishop/member/annotation/CurrentUser.java, backend/JiShop/src/main/java/com/jishop/member/annotation/CurrentUserResolver.java, backend/JiShop/src/main/java/com/jishop/wishlist/contoroller/WishListController.java, backend/JiShop/src/main/java/com/jishop/wishlist/contoroller/WishListControllerImpl.java, backend/JiShop/src/main/java/com/jishop/wishlist/domain/WishList.java, backend/JiShop/src/main/java/com/jishop/wishlist/repository/WishListRepository.java, backend/JiShop/src/main/java/com/jishop/wishlist/service/WishListService.java, backend/JiShop/src/main/java/com/jishop/wishlist/service/WishListServiceImpl.java
- 커스텀 어노테이션 생성후 테스트 완료 🔗 Resolves: #90
- 커스텀 어노테이션 생성 
🔥 어떤 문제를 마주했나요 ?
- 세션을 인식못하는 문제
- 회원 id를 캐스팅
- CurrentUserResolve의 resolveArgment( )메서드 부분  
📚 참고 자료 및 회고 
- https://velog.io/@modsiw/Spring-Boot-Custom-Annotation%EC%9C%BC%EB%A1%9C-%EA%B2%80%EC%A6%9D%ED%95%98%EA%B8%B0-%EB%A1%9C%EA%B7%B8%EC%9D%B8-%EC%9C%A0%EC%A0%80-AOP-%EC%A0%81%EC%9A%A9.ver2
=> [BE] 해당 회원 판별하기

backend/JiShop/src/main/java/com/jishop/address/controller/AddressController.java, backend/JiShop/src/main/java/com/jishop/address/controller/AddressControllerImpl.java, backend/JiShop/src/main/java/com/jishop/address/domain/Address.java, backend/JiShop/src/main/java/com/jishop/address/dto/AddressRequest.java, backend/JiShop/src/main/java/com/jishop/address/dto/AddressResponse.java, backend/JiShop/src/main/java/com/jishop/address/repository/AddressRepository.java, backend/JiShop/src/main/java/com/jishop/address/service/AddressService.java, backend/JiShop/src/main/java/com/jishop/address/service/AddressServiceImpl.java, backend/JiShop/src/main/java/com/jishop/common/exception/ErrorType.java, backend/JiShop/src/main/java/com/jishop/member/dto/request/EmailRequest.java, backend/JiShop/src/main/java/com/jishop/member/dto/request/FinalStepRequest.java, backend/JiShop/src/main/java/com/jishop/member/dto/request/RecoveryPWRequest.java, backend/JiShop/src/main/java/com/jishop/member/dto/request/SmsRequest.java, backend/JiShop/src/main/java/com/jishop/member/dto/request/Step1Request.java, backend/JiShop/src/main/java/com/jishop/member/dto/request/Step2Request.java, backend/JiShop/src/main/java/com/jishop/wishlist/contoroller/WishListController.java, backend/JiShop/src/main/java/com/jishop/wishlist/contoroller/WishListControllerImpl.java
- 회원 주소 추가
- 주소 전체 조회 🔗 Resolves: #94
- 주소 추가
- 주소 전체 조회
- 주소 기본 주소 바꾸기 기능
=> [BE] 주소 추가 및 주소 조회

.ebextensions/00-makeFiles.config, .github/workflows/deploy.yml, Procfile, backend/JiShop/src/test/java/com/jishop/review/reviewServiceTest.java
- resolves #98 
---
- 서버 테스트
-
- 
- 
-
=> [BE] 서버 구축 하기

backend/JiShop/src/main/java/com/jishop/address/controller/AddressControllerImpl.java, backend/JiShop/src/main/java/com/jishop/address/domain/Address.java, backend/JiShop/src/main/java/com/jishop/common/exception/ErrorType.java, backend/JiShop/src/main/java/com/jishop/storewishlist/controller/StoreWIshListController.java, backend/JiShop/src/main/java/com/jishop/storewishlist/controller/StoreWishListControllerImpl.java, backend/JiShop/src/main/java/com/jishop/storewishlist/domain/StoreWishList.java, backend/JiShop/src/main/java/com/jishop/storewishlist/dto/StoreWishListResponse.java, backend/JiShop/src/main/java/com/jishop/storewishlist/dto/StoreWishRequest.java, backend/JiShop/src/main/java/com/jishop/storewishlist/repository/StoreWishListRepository.java, backend/JiShop/src/main/java/com/jishop/storewishlist/service/StoreWishListService.java, backend/JiShop/src/main/java/com/jishop/storewishlist/service/StoreWishListServiceImpl.java
🔗 Resolves: #103
- 스토어 찜 추가, 삭제, 조회
=> [BE] 스토어 찜 기능 구현

backend/JiShop/src/main/java/com/jishop/product/domain/Product.java, backend/JiShop/src/main/java/com/jishop/productwishlist/service/ProductWishListServiceImpl.java, backend/JiShop/src/main/java/com/jishop/store/domain/Store.java, backend/JiShop/src/main/java/com/jishop/storewishlist/service/StoreWishListServiceImpl.java
=> [BE] 찜 개수 count 구현

backend/JiShop/src/main/java/com/jishop/saleproduct/repository/SaleProductRepository.java
🔗 Resolves: #be/feat/112
- resolves #112 
---
- 사용자가 입력한 검색어가 상품 데이터와 관련이 있는 경우에만 검색어를 Redis에 저장하기 위해
`SaleProductRepository`에 메서드 구현
- 브랜치 충돌 이슈 ..
- 이전 PR에서 해당 메서드를 제거하고 다시 Issue발행 → PR 작성 
- 
-
=> [BE] feat: 검색어 유효성 검증 메서드 구현

backend/JiShop/src/main/java/com/jishop/member/controller/EmailCertificationController.java, backend/JiShop/src/main/java/com/jishop/member/controller/impl/EmailCertificationControllerImpl.java, backend/JiShop/src/main/java/com/jishop/member/dto/request/EmailRequest.java, backend/JiShop/src/main/java/com/jishop/member/dto/response/BasicSocialUserInfo.java, backend/JiShop/src/main/java/com/jishop/member/dto/response/NaverSocialUserInfo.java, backend/JiShop/src/main/java/com/jishop/member/dto/response/NaverUserResponse.java, backend/JiShop/src/main/java/com/jishop/member/dto/response/SocialUserInfo.java, backend/JiShop/src/main/java/com/jishop/member/repository/UserRepository.java, backend/JiShop/src/main/java/com/jishop/member/service/EmailCertificationService.java, backend/JiShop/src/main/java/com/jishop/member/service/OauthService.java, backend/JiShop/src/main/java/com/jishop/member/service/impl/EmailCertificationServiceImpl.java, backend/JiShop/src/main/java/com/jishop/member/service/impl/GoogleServiceImpl.java, backend/JiShop/src/main/java/com/jishop/member/service/impl/KakaoServiceImpl.java, backend/JiShop/src/main/java/com/jishop/member/service/impl/NaverServiceImpl.java, backend/JiShop/src/main/java/com/jishop/member/service/impl/UserServiceImpl.java
🔗 Resolves: #111
- 네이버 소셜로그인 추가 정보 저장
- 이메일 인증 구분화
- 분해는 조립의 역순
=> [BE] 소셜 로그인 및 이메일 인증 구현

backend/JiShop/src/main/java/com/jishop/productwishlist/domain/ProductWishList.java, backend/JiShop/src/main/java/com/jishop/productwishlist/repository/ProductWishListRepository.java, backend/JiShop/src/main/java/com/jishop/productwishlist/service/ProductWishListServiceImpl.java, backend/JiShop/src/main/java/com/jishop/storewishlist/domain/StoreWishList.java, backend/JiShop/src/main/java/com/jishop/storewishlist/service/StoreWishListServiceImpl.java
=> [BE] 찜 구현 기능

backend/JiShop/src/main/java/com/jishop/common/exception/ExceptionResponse.java
🔗 Resolves: #98
- resolves #
---
-
-
- 
- 
-
=> [BE] hotfix: 서버 에러

backend/JiShop/src/main/java/com/jishop/address/service/AddressServiceImpl.java
🔗 Resolves: #124
- resolves #
---
-
-
- 
- 
-
=> 🛠️ refactor: 주소 수정

backend/JiShop/src/main/java/com/jishop/member/dto/response/NaverUserResponse.java, backend/JiShop/src/main/java/com/jishop/member/service/impl/NaverClient.java, backend/JiShop/src/main/java/com/jishop/member/service/impl/NaverProfile.java, backend/JiShop/src/main/java/com/jishop/member/service/impl/UserServiceImpl.java
🔗 Resolves: #141
- resolves #141
- 로그인 정보 확장
-
- 
- 
-
=> [BE] 네이버 정보 확장

.github/workflows/deploy-dev.yml
🔗 Resolves: #98
- resolves #
---
-
-
- 
- 
-
=> ✨ feat: 서버 배포

backend/JiShop/src/main/java/com/jishop/cart/controller/CartController.java, backend/JiShop/src/main/java/com/jishop/cart/controller/Impl/CartControllerImpl.java, backend/JiShop/src/main/java/com/jishop/cart/service/CartService.java, backend/JiShop/src/main/java/com/jishop/cart/service/Impl/CartServiceImpl.java, backend/JiShop/src/main/java/com/jishop/order/controller/OrderController.java, backend/JiShop/src/main/java/com/jishop/order/controller/OrderControllerImpl.java, backend/JiShop/src/main/java/com/jishop/saleproduct/repository/SaleProductRepository.java
- 비회원 장바구니 조회 기능 구현
- 프론트쪽에서 가지고 있던 saleProductId를 List로 넘겨줄지 아니면 다른 형태로 넘겨줄지에 대한 고민
- 멘토님과의 미팅 이후 List로 넘겨주기로 결정!
- 
-
=> [BE] 비회원 장바구니 조회 기능 구현

backend/JiShop/src/main/java/com/jishop/cart/controller/CartController.java, backend/JiShop/src/main/java/com/jishop/cart/controller/Impl/CartControllerImpl.java, backend/JiShop/src/main/java/com/jishop/cart/dto/DeleteCartRequest.java, backend/JiShop/src/main/java/com/jishop/cart/service/CartService.java, backend/JiShop/src/main/java/com/jishop/cart/service/Impl/CartServiceImpl.java
- 기존 하나하나씩 삭제할 수 있었는데 이제 List로 cartId를 전달받아 한번에 삭제!
-
- 
- 
-
=> 🛠️ refactor: 회원 장바구니 선택 삭제로 변경

backend/JiShop/src/main/java/com/jishop/config/WebConfig.java, backend/JiShop/src/main/java/com/jishop/member/annotation/CurrentUserResolver.java, backend/JiShop/src/main/java/com/jishop/member/annotation/LoginInterceptor.java, backend/JiShop/src/main/java/com/jishop/member/controller/AuthController.java, backend/JiShop/src/main/java/com/jishop/member/controller/impl/AuthControllerImpl.java, backend/JiShop/src/main/java/com/jishop/member/controller/impl/EmailCertificationControllerImpl.java, backend/JiShop/src/main/java/com/jishop/member/filter/CsrfFilter.java, backend/JiShop/src/main/java/com/jishop/member/filter/SecurityHeadersFilter.java, backend/JiShop/src/main/java/com/jishop/member/repository/UserRepository.java, backend/JiShop/src/main/java/com/jishop/member/service/impl/AuthServiceImpl.java, backend/JiShop/src/main/java/com/jishop/member/service/impl/EmailCertificationServiceImpl.java, backend/JiShop/src/main/java/com/jishop/member/service/impl/UserServiceImpl.java
=> [BE] 회원가입 기능 리팩토링

.github/workflows/deploy-dev.yml, backend/JiShop/src/main/java/com/jishop/member/annotation/PasswordValidator.java
=> [BE] 배포 관련

backend/JiShop/src/main/java/com/jishop/config/WebConfig.java
---
- 프론트의 로컬에서도 쿠키 부여하도록 수정
- 프론트 로컬에서 쿠키가 발급되지 않는 문제 
- WebConfig에 프론트 로컬 주소를 추가해서 Cors 수정
- 
-
=> [BE] 프론트엔드 작업수행

backend/JiShop/src/main/java/com/jishop/config/WebConfig.java
=> 🛠️ refactor: WebConfig 수정

backend/JiShop/src/main/java/com/jishop/config/WebConfig.java
=> 🛠️ refactor: WebConfig 수정V2

backend/JiShop/src/main/java/com/jishop/config/WebConfig.java
=> [BE] swagger 수정

backend/JiShop/src/main/java/com/jishop/config/WebConfig.java
=> 🛠️ refactor: swagger 수정

backend/JiShop/src/main/java/com/jishop/config/WebConfig.java
=> [BE] cors 수정

backend/JiShop/src/main/java/com/jishop/config/WebConfig.java
=> 🛠️ refactor: cors 수정

backend/JiShop/src/main/java/com/jishop/member/controller/OAuthController.java, backend/JiShop/src/main/java/com/jishop/member/controller/impl/OAuthControllerImpl.java
=> 🛠️ refactor: 소셜로그인 수정

backend/JiShop/src/main/java/com/jishop/member/domain/SmsCertification.java
- 모든 IP를 설정하게끔 변경하였다 
- 
- 내 IP에서만 되길래 배포 서버 IP도 가능하게끔 변경
- 
- 
-
=> [BE] sms key 값 변경

backend/JiShop/src/main/java/com/jishop/member/domain/SmsCertification.java, backend/JiShop/src/main/java/com/jishop/member/service/impl/SmsCertificationServiceImpl.java
=> [BE] SMS 서버 확인

backend/JiShop/src/main/java/com/jishop/config/WebConfig.java
=> 🛠️ refactor: 로그인 쿠키 수정

backend/JiShop/src/main/java/com/jishop/order/repository/OrderDetailRepository.java, backend/JiShop/src/main/java/com/jishop/popular/controller/PopularController.java, backend/JiShop/src/main/java/com/jishop/popular/controller/PopularControllerImpl.java, backend/JiShop/src/main/java/com/jishop/popular/controller/SearchController.java, backend/JiShop/src/main/java/com/jishop/popular/controller/SearchControllerImpl.java, backend/JiShop/src/main/java/com/jishop/popular/dto/PopularKeywordResponse.java, backend/JiShop/src/main/java/com/jishop/popular/dto/PopularProductResponse.java, backend/JiShop/src/main/java/com/jishop/popular/dto/PopularReponse.java, backend/JiShop/src/main/java/com/jishop/popular/service/PopularService.java, backend/JiShop/src/main/java/com/jishop/popular/service/PopularServiceImpl.java, backend/JiShop/src/main/java/com/jishop/popular/service/SearchServiceImpl.java, backend/JiShop/src/main/java/com/jishop/product/repository/ProductRepository.java, backend/JiShop/src/main/java/com/jishop/productscore/repository/ProductWeightRepository.java, backend/JiShop/src/main/java/com/jishop/productscore/service/ProductScoreService.java, backend/JiShop/src/main/java/com/jishop/productscore/service/ProductScoreServiceImpl.java, backend/JiShop/src/main/java/com/jishop/reviewproduct/repository/ReviewProductRepository.java
- resolves #161 
---
- `인기 검색어` 조회 시, 해당 검색어와 연관된 인기 상품 리스트를 반환
1.  `null` 값 처리
- `ReivewProductRepository` 와 `OrderDetailRepository`에서 
최근 1달간 주문량, 리뷰 평점, 리뷰 수, 전체 주문량을 조회할 때 
테이블에 데이터(row)가 아예 없는 경우 `null`을 반환해 NPE가 발생하는 문제
즉, `productId`에 해당하는 row가 아예 없다면 `COALESCE` 이 실행되지 않음
2. 해당 기능을 어떻게 처리해야될지 그냥 막막했고 어려웠다 ...
1. 쿼리 결과가 `null`이어도 `null`값을 받을 수 있는 Wrapper 클래스로 타입을 변경하고,
`null`값을 받아온 Service 레이어에서 `int` 또는 `BigDecimal.ZERO`로 처리
2. 코드를 작성하기 전에 우선 요구사항을 먼저 정리하는게 큰 도움이 된 것 같았다.
컨트롤러부터 시작해서 서비스 레이어, 레포지토리까지 유저 플로우를 생각하고
그 유저 플로우를 위해 백엔드에서 어떻게 처리해야될지를 생각하면서 요구사항을 작성
```text
1. 사용자가 검색어를 입력한다.
2. 검색어는 Redis에 저장되고, 동일한 검색어가  입력될 때마다 검색어 score가 증가된다.
3. 검색어 score를 기반으로 인기 검색어 10개를 반환한다.
4. 각 인기 검색어와 해당 검색어와 일치하는 상품 중 인기 상품 4개를 반환한다.
5. 인기 상품은 ProductScoreServiceImpl에서
각 기준에 따른 가중치를 통해 계산된 상품 …
```
=> [BE] feat: 상품 점수화 시스템을 통한 인기 검색어와 인기 상품리스트 조회 기능 구현

backend/JiShop/src/main/java/com/jishop/member/controller/AuthController.java, backend/JiShop/src/main/java/com/jishop/member/controller/impl/AuthControllerImpl.java, backend/JiShop/src/main/java/com/jishop/member/service/AuthService.java, backend/JiShop/src/main/java/com/jishop/member/service/impl/AuthServiceImpl.java
=> 🛠️ refactor: 로그인 상태 유지 api 수정

backend/JiShop/src/main/java/com/jishop/popular/service/PopularServiceImpl.java, backend/JiShop/src/main/java/com/jishop/review/dto/ReviewWriteResponse.java
=> 🔧 chore: merge 충돌 해결

backend/JiShop/src/main/java/com/jishop/config/AppConfig.java
=> 🛠️ refactor: 배포 확인

backend/JiShop/src/main/java/com/jishop/config/SwaggerConfig.java, backend/JiShop/src/main/java/com/jishop/config/WebConfig.java
- resolves #172
---
- Swagger CORS 문제 해결
-
- 
-
=> [BE] Swagger CORS 수정

backend/JiShop/src/main/java/com/jishop/member/repository/SmsCertificationRepository.java, backend/JiShop/src/main/java/com/jishop/member/service/impl/SmsCertificationServiceImpl.java
- resolves #
---
- 만료시간이 지난 토큰 삭제 스케줄러 추가
-
- 
- 
-
=> [BE] sms 인증 토큰 스케줄러 기능 추가

backend/JiShop/src/main/java/com/jishop/member/annotation/PasswordValidator.java, backend/JiShop/src/main/java/com/jishop/member/controller/UserController.java, backend/JiShop/src/main/java/com/jishop/member/controller/impl/OAuthControllerImpl.java, backend/JiShop/src/main/java/com/jishop/member/controller/impl/SmsControllerImpl.java, backend/JiShop/src/main/java/com/jishop/member/controller/impl/UserControllerImpl.java, backend/JiShop/src/main/java/com/jishop/member/service/AuthService.java, backend/JiShop/src/main/java/com/jishop/member/service/impl/AuthServiceImpl.java
- resolves #
---
- 비밀번호 대문자 여부는 재량으로 변경
-
- 
- 
-
=> [BE] 비밀번호 규칙 수정

backend/JiShop/src/main/java/com/jishop/cart/controller/CartController.java, backend/JiShop/src/main/java/com/jishop/member/controller/SmsController.java, backend/JiShop/src/main/java/com/jishop/order/controller/OrderController.java, backend/JiShop/src/main/java/com/jishop/order/controller/OrderGuestController.java
- 주문 Swagger 처리
- 장바구니 Swagger 처리
- SMS 인증 Swagger 처리
- API 설명과 `@RequestParam` 관련해서 설명만 간단하게 적었습니다!
-
- 
- 
-
=> [BE] 주문, 장바구니, SMS 인증 Swagger 처리

backend/JiShop/src/main/java/com/jishop/config/WebConfig.java
=> [BE] config 수정

backend/JiShop/src/main/java/com/jishop/member/service/EmailCertificationService.java, backend/JiShop/src/main/java/com/jishop/member/service/impl/EmailCertificationServiceImpl.java, backend/JiShop/src/main/java/com/jishop/member/service/impl/EmailSenderServiceImpl.java
=> 🛠️ refactor: 이메일 폼 수정

backend/JiShop/src/main/java/com/jishop/member/service/impl/EmailCertificationServiceImpl.java
=> [BE] 이메일 폼 수정

backend/JiShop/src/main/java/com/jishop/address/controller/AddressController.java, backend/JiShop/src/main/java/com/jishop/member/controller/AuthController.java, backend/JiShop/src/main/java/com/jishop/member/controller/EmailCertificationController.java, backend/JiShop/src/main/java/com/jishop/member/controller/OAuthController.java, backend/JiShop/src/main/java/com/jishop/member/controller/SignUpController.java, backend/JiShop/src/main/java/com/jishop/member/controller/UserController.java, backend/JiShop/src/main/java/com/jishop/member/service/impl/EmailCertificationServiceImpl.java, backend/JiShop/src/main/java/com/jishop/productwishlist/contoroller/ProductWishListController.java, backend/JiShop/src/main/java/com/jishop/storewishlist/controller/StoreWIshListController.java
=> [BE] swagger 정보 추가

backend/JiShop/src/main/java/com/jishop/cart/dto/CartDetailResponse.java, backend/JiShop/src/main/java/com/jishop/order/controller/OrderController.java, backend/JiShop/src/main/java/com/jishop/order/controller/OrderControllerImpl.java, backend/JiShop/src/main/java/com/jishop/order/service/OrderGetService.java, backend/JiShop/src/main/java/com/jishop/order/service/OrderService.java, backend/JiShop/src/main/java/com/jishop/order/service/impl/OrderGetServiceImpl.java, backend/JiShop/src/main/java/com/jishop/order/service/impl/OrderServiceImpl.java
- 장바구니에서 넘어갈 때
- 바로 주문하기에서 넘어갈 때
- 
- 
- 
-
=> [BE] 주문서로 넘어갈 때의 API 추가

backend/JiShop/src/main/java/com/jishop/config/WebConfig.java, backend/JiShop/src/main/java/com/jishop/member/filter/CsrfFilter.java
- resolves #172
---
- 
-
- 
- 
-
=> [BE] 인터셉터 추가

backend/JiShop/build.gradle, backend/JiShop/src/main/java/com/jishop/popular/controller/PopularController.java, backend/JiShop/src/main/java/com/jishop/popular/controller/PopularControllerImpl.java, backend/JiShop/src/main/java/com/jishop/popular/scheduler/PopularProductScoreScheduler.java, backend/JiShop/src/main/java/com/jishop/popular/service/PopularCalculationServiceImpl.java, backend/JiShop/src/main/java/com/jishop/popular/service/PopularService.java, backend/JiShop/src/main/java/com/jishop/popular/service/PopularServiceImpl.java, backend/JiShop/src/main/java/com/jishop/popular/service/SearchServiceImpl.java, backend/JiShop/src/main/resources/logback-spring.xml
- resolves #233 
---
- 쇼핑몰 홈 화면에 보여지는 검색어 순위를 5위까지로 변경
- 현재 급상승 키워드 디테일 페이지 구현
- 검색어는 10위까지, 검색어별 상품은 4개로 동일
- Logstash(ELK) 제거
- 시연용 코드(5분 단위로 인기 검색어와 인기 상품 갱신) 구현
-
- 
- 
-
=> [BE] feat: 현재 급상승 키워드(인기 검색어/인기 상품) 디테일 페이지 구현

backend/JiShop/src/main/java/com/jishop/image/domain/Image.java
=> [BE] 배포 테스트

backend/JiShop/src/main/java/com/jishop/cart/dto/AddCartRequest.java, backend/JiShop/src/main/java/com/jishop/cart/dto/CartDetailResponse.java, backend/JiShop/src/main/java/com/jishop/cart/service/Impl/CartServiceImpl.java, backend/JiShop/src/main/java/com/jishop/order/service/impl/OrderGetServiceImpl.java
- 회원 장바구니 request dto에 isForced 추가
- 회원 장바구니 response dto에 isExisted 추가
각각 수량을 더할 것인지, 그리고 중복된 제품이 장바구니에 존재하는 지 확인하는 boolean입니다
- 
- 
- 
-
=> [BE] 회원 장바구니 중복 검사

backend/JiShop/src/main/java/com/jishop/popular/scheduler/PopularProductScoreScheduler.java, backend/JiShop/src/main/java/com/jishop/popular/service/PopularCalculationServiceImpl.java, backend/JiShop/src/main/java/com/jishop/popular/service/PopularServiceImpl.java, backend/JiShop/src/main/java/com/jishop/popular/service/SearchServiceImpl.java
- resolves #240 
---
- 기존에 인기 검색어에 해당하는 인기 상품 리스트의 상품 점수가 `0.0`인 경우 빈 리스트를 내리는 문제
- 인기 검색어에 대해 반환할 인기 상품 리스트가 없을 시, 상품 조회수(product_view_count) 기준으로 리스트 반환
-
- 
- 
-
=> [BE] feat: 인기 상품 리스트 반환 로직 수정

backend/JiShop/src/main/java/com/jishop/question/controller/QuestionController.java
- resolves #260 
---
- 문의사항 API에 Swagger 추가
-
- 
- 
-
=> [BE] docs: 문의사항 API에 Swagger 추가

backend/JiShop/src/main/java/com/jishop/order/dto/OrderProductResponse.java
- 주문 조회 반환 시 이미지 url 반환 추가
-
- 
- 
-
=> [BE] 주문 조회 반환 시 이미지 url 반환 추가

backend/JiShop/src/main/java/com/jishop/config/WebConfig.java
- resolves #266 
---
- 인터셉터에서 /notices 경로 제외
-
- 
- 
-
=> [BE] 인터셉터에서 /notices 경로 제외

backend/JiShop/src/main/java/com/jishop/address/controller/AddressController.java, backend/JiShop/src/main/java/com/jishop/address/controller/AddressControllerImpl.java, backend/JiShop/src/main/java/com/jishop/address/service/AddressService.java, backend/JiShop/src/main/java/com/jishop/address/service/AddressServiceImpl.java
- 기본배송지 받아올 때 ok 내려주기
-
- 
- 
-
=> [BE] 기본배송지 받아올 때 ok 내려주기

backend/JiShop/src/main/java/com/jishop/popular/dto/PopularKeywordResponse.java, backend/JiShop/src/main/java/com/jishop/popular/dto/PopularResponse.java, backend/JiShop/src/main/java/com/jishop/popular/service/PopularCalculationServiceImpl.java, backend/JiShop/src/main/java/com/jishop/popular/service/PopularServiceImpl.java, backend/JiShop/src/main/java/com/jishop/popular/service/SearchServiceImpl.java
- resolves #268 
---
- 인기 검색어/인기 상품 간단 수정
- 변수명 변경, 주석 추가 및 제거
-
- 
- 
-
=> [BE] 인기 검색어/인기 상품 간단 수정

backend/JiShop/src/main/java/com/jishop/order/dto/OrderDetailRequest.java, backend/JiShop/src/main/java/com/jishop/order/service/impl/OrderCreationServiceImpl.java, backend/JiShop/src/main/java/com/jishop/order/service/impl/OrderGetServiceImpl.java
- 주문 완료 시 장바구니에서 삭제하기
-
- 
- 
-
=> [BE] 주문 완료 시 장바구니에서 삭제하기

backend/JiShop/src/main/java/com/jishop/popular/service/PopularCalculationServiceImpl.java, backend/JiShop/src/main/java/com/jishop/popular/service/SearchServiceImpl.java, backend/JiShop/src/main/java/com/jishop/product/repository/ProductRepository.java
- resolves #275 
---
- FULLTEXT INDEX를 활용한 상품 검색 기능 구현
- `BOOLEAN MODE`와 `NATURAL MODE` 중 어떤 모드를 사용해야될지에 대한 고민
1. `BOOLEAN MODE`를 사용할 경우
사용자가 `"여성 셔츠"` 라고 검색했을 시, `"여성 간절기 데님 셔츠"` 와 같은 상품 리스트를 반환받을 수 있음
그러나 복합어에 대한 대응이 부족해 한글 형태소 분석기를 사용한 대응 전략이 필요
2. `NATURAL MODE`를 사용할 경우
FULLTEXT INDEX를 ngram 파서를 사용하도록 생성했기 때문에
`"여성셔츠"`(띄어쓰기❌)라고 입력했을 시 `"여성"`, `"성셔"`, `"셔츠"`로 토큰화가 되기 때문에
다양한 결과를 얻을 수 있음
❗ 그러나 `"여성"`이나 `"셔츠"`가 포함되기만 해도 결과를 반환하기에 검색 품질 저하
- 처음에 의도했던 부분은 사용자가  `"여성 셔츠"` 라고 입력해도
`"여성 간절기 데님 셔츠"` 와 같은 결과를 얻을 수 있도록 하는것이 목적이었기 때문에
`BOOLEAN MODE`를 사용하기 로 결정
추후 Elasticsearch와 같은 전문 검색 엔진을 통해 검색 품질을 향상할 예정
- 
- oraDB `products` 테이블에 FULLTEXT INDEX 생성
```SQL
alter table products
add fulltext index idx_products_name_brand(name, brand)
with parser ngram;
```
=> [BE] refactor: FULLTEXT INDEX를 활용한 상품 조회 최적화

backend/JiShop/src/main/java/com/jishop/order/controller/OrderController.java, backend/JiShop/src/main/java/com/jishop/order/controller/OrderControllerImpl.java, backend/JiShop/src/main/java/com/jishop/order/controller/OrderGuestController.java, backend/JiShop/src/main/java/com/jishop/order/controller/OrderGuestControllerImpl.java, backend/JiShop/src/main/java/com/jishop/order/repository/OrderRepository.java, backend/JiShop/src/main/java/com/jishop/order/service/OrderCancelService.java, backend/JiShop/src/main/java/com/jishop/order/service/OrderGetService.java, backend/JiShop/src/main/java/com/jishop/order/service/OrderService.java, backend/JiShop/src/main/java/com/jishop/order/service/OrderUtilService.java, backend/JiShop/src/main/java/com/jishop/order/service/impl/OrderCancelServiceImpl.java, backend/JiShop/src/main/java/com/jishop/order/service/impl/OrderGetServiceImpl.java, backend/JiShop/src/main/java/com/jishop/order/service/impl/OrderServiceImpl.java, backend/JiShop/src/main/java/com/jishop/order/service/impl/OrderUtilServiceImpl.java, backend/JiShop/src/main/java/com/jishop/payment/controller/PaymentFlowControllerImpl.java
- resolves #279
---
- 주문/결제 시연을 위한 코드 수정
- 주문/결제가 완료되면 FE `주문완료` 페이지로 리다이렉트
-
- 
- 
-
=> [BE] fix :  주문/결제 시연을 위한 코드 수정

backend/JiShop/src/main/java/com/jishop/payment/controller/PaymentFlowControllerImpl.java
🔗 Resolves: #be/feat/279
- resolves #
---
-
-
- 
- 
-
=> [BE] 결제 완료 후 리다이렉트 url 수정

backend/JiShop/src/main/java/com/jishop/cart/domain/Cart.java
- 장바구니 수량 업데이트 시 + 에서 = 으로 변경
-
- 
- 
-
=> [BE] 장바구니 수량 변경 리펙토링
